version: "3"

services:

  group19_telegram_bot:
    container_name: group19_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile